### PR TITLE
Update twelveToneBasics.md

### PR DESCRIPTION
**Pull request by bryanagee**
Just added a missing "is" to into paragraph.

### CODE REVIEW

**Comment by kshaffer** [comment]
Thanks, Bryan! Though as soon as I merged this, I realized that this is our old repo. Because of some weird GitHub-matching-domain-name issues, we moved it to its own organization: https://github.com/openmusictheory/openmusictheory.github.io. Now I'm suspicious that I left an old link somewhere. Did you follow a link here, or just search and find it?

**Comment by kshaffer** [comment]
Just found the incorrect link in the about page. I'll fix that now. (Unless you came from another one?)

**Comment by bryanagee** [comment]
I followed a link from about 2/5 down this page:
http://openmusictheory.com/about.html . I will update my fork. Thanks!

**Comment by kshaffer** [comment]
Awesome. I just fixed that link (and the edit you made) in the correct repo. I'll check with the others and see if we still need this one. Probably best to delete it if not.

Thanks for the help!

Kris

**Comment by bryanagee** [comment]
Any time--it's a very cool project. Hopefully I will have time to edit more
than just one word in the future =)

**Pull request merged**
